# Graphs and their representation

Graphs are commonly used data structure, used for representing relationships between various items. There are two common representations for graphs: adjacency lists and adjacency matrices. The first represents graphs as a list per node, containing the node's neighbours; the second represents graphs as a square matrix, with number of columns and number of rows equal to the number of vertices in the graph, with values zero for cells $(i,j)$ if $i$ and $j$ are not connected and $(i,j)$ equal to 1 otherwise. (If we add weights to edges, this value will not necessarily be 1, but we return to that in the exercises).

One approach to constructing a graph based on adjacency lists could be this:

In [6]:
def make_list_graph(n_vertices):
    return [[] for _ in range(n_vertices)]
    
def add_list_edge(graph, source, target):
    if target not in graph[source]:
        graph[source].append(target)

You shouldn't use this expression to construct a list of lists

```python
[[]] * n
```

Multiplying a list by a number creates a list with the values of the old list repeated that number of times, but the elements we repeat are references to the same elements. This is not a problem with immutable values like numbers, but with lists, it means we get a list of the *same* list, repeated. If we modify one of the entries, we modify them all:

In [7]:
x = [[]] * 5
print(x)
x[0].append(1)
print(x)

[[], [], [], [], []]
[[1], [1], [1], [1], [1]]


By using the list comprehension, we create a new empty list for each vertex in the graph.

In [8]:
x = [[] for _ in range(6)]
print(x)
x[0].append(1)
print(x)

[[], [], [], [], [], []]
[[1], [], [], [], [], []]


We can construct an example graph like this:

In [9]:
g = make_list_graph(6)

add_list_edge(g, 0, 1)
add_list_edge(g, 0, 5)
add_list_edge(g, 1, 2)
add_list_edge(g, 1, 3)
add_list_edge(g, 2, 4)
add_list_edge(g, 3, 5)
add_list_edge(g, 5, 1)

print(g)

[[1, 5], [2, 3], [4], [5], [], [1]]


Adjacency lists make it easy to find out the degrees of each node and for traversing graphs, and if the graph is sparse, this representation is more memory efficient. Adjacency matrices, on the other hand, makes it constant time operations to check for the existance of edges and for inserting and removing edges. For adjacancy matrices, we can use the following functions:

In [11]:
import numpy as np

def make_matrix_graph(n_vertices):
    return np.zeros(shape = (n_vertices, n_vertices), dtype=int)

def add_matrix_edge(graph, i, j):
    graph[i,j] = 1

In [12]:
g = make_matrix_graph(6)

add_matrix_edge(g, 0, 1)
add_matrix_edge(g, 0, 5)
add_matrix_edge(g, 1, 2)
add_matrix_edge(g, 1, 3)
add_matrix_edge(g, 2, 4)
add_matrix_edge(g, 3, 5)
add_matrix_edge(g, 5, 1)

print(g)

[[0 1 0 0 0 1]
 [0 0 1 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 1 0 0 0 0]]


The implementations above assume that the edges in the graphs are orientated, that means that the existance of an edge $(v,w)$ does not imply the existance of $(w,v)$. If this is what you need, you can simply modify the `add_edge` functions to insert the inverse of the indices we insert as well.